import {
  auditApi, bondedApi, customsApi, inboundApi, inventoryApi, materialApi, ocrApi,
  outboundApi, partnerApi, productionApi, stocktakeApi, warehouseApi, authApi,
} from '@/api'
import type { DetailBlock, ModuleSchema } from '@/types'

const consignors = ['五矿有色', '广西金川', '广西南国']
const houses = ['1仓', '2仓', '4仓', '5仓', '6仓', '码头仓库']
const areas = ['原料区', '待检区', '成品区']
const stackCodes = ['1#A1', '1#A2', '2#A1', '4#A1', '4#B1', '5#A1', '6#A1', '码头#A1']
const customsNos = ['5301202600001234', '5301202600002234', '5301202600003234', '5301202600004234']

function text(value: unknown) {
  if (value == null || value === '') return '—'
  return String(value)
}

export const schemas: Record<string, ModuleSchema> = {
  warehouses: {
    key: 'warehouses',
    createLabel: '新建仓库',
    filters: [
      { key: 'keyword', label: '仓库编号', placeholder: '如 1仓 / 码头仓库' },
      { key: 'status', label: '状态', type: 'select', options: ['启用', '停用'] },
    ],
    columns: [
      { prop: 'code', label: '仓库编号', minWidth: 120 },
      { prop: 'capacity', label: '库容(吨)', width: 120 },
      { prop: 'area', label: '面积(㎡)', width: 120 },
      { prop: 'stackCount', label: '堆位数', width: 90 },
      { prop: 'rate', label: '已用/占用率', minWidth: 180, usage: true },
      { prop: 'status', label: '状态', width: 90, tag: true },
    ],
    form: [
      { key: 'code', label: '仓库编号', required: true, disabled: (_form, isEdit) => isEdit },
      { key: 'capacity', label: '库容(吨)', type: 'number', required: true },
      { key: 'area', label: '面积(㎡)', type: 'number', required: true, placeholder: '仅展示，不参与占用' },
      { key: 'status', label: '状态', type: 'select', options: ['启用', '停用'], required: true },
    ],
    list: warehouseApi.list,
    create: warehouseApi.create,
    update: warehouseApi.update,
    actions: [{ label: '查看堆位', path: '/stacks', queryKey: 'warehouse', queryFrom: 'code' }],
  },
  stacks: {
    key: 'stacks',
    createLabel: '新建堆位',
    filters: [
      { key: 'warehouse', label: '仓库', type: 'select', options: houses },
      { key: 'areaLabel', label: '片区标识', type: 'select', options: areas },
      { key: 'keyword', label: '堆位编码', placeholder: '如 4#A1' },
    ],
    columns: [
      { prop: 'code', label: '编码', minWidth: 120 },
      { prop: 'warehouse', label: '所属仓库', width: 120 },
      { prop: 'areaLabel', label: '片区标识', width: 120, tag: true },
      { prop: 'grid', label: '网格', width: 100 },
      { prop: 'capacity', label: '库容(吨)', width: 120 },
      { prop: 'status', label: '状态', width: 90, tag: true },
    ],
    form: [
      { key: 'code', label: '堆位编码', required: true, disabled: (_f, isEdit) => isEdit },
      { key: 'warehouse', label: '所属仓库', type: 'select', options: houses, required: true },
      { key: 'areaLabel', label: '片区标识', type: 'select', options: areas, required: true },
      { key: 'capacity', label: '库容(吨)', type: 'number', required: true },
      { key: 'status', label: '状态', type: 'select', options: ['启用', '停用'], required: true },
    ],
    list: warehouseApi.stacks,
    create: warehouseApi.createStack,
    update: warehouseApi.updateStack,
  },
  materials: {
    key: 'materials',
    createLabel: '新建物料',
    filters: [
      { key: 'keyword', label: '编码/名称' },
      { key: 'kind', label: '类型', type: 'select', options: ['原料', '成品'] },
    ],
    columns: [
      { prop: 'code', label: '编码', minWidth: 140 },
      { prop: 'name', label: '名称', minWidth: 160 },
      { prop: 'cargoType', label: '货物类型', width: 120 },
      { prop: 'kind', label: '类型', width: 100 },
      { prop: 'source', label: '矿源', minWidth: 140 },
    ],
    form: [
      { key: 'code', label: '物料编码', required: true, placeholder: '如 CU-RAW-01', disabled: (_f, isEdit) => isEdit },
      { key: 'name', label: '名称', required: true },
      { key: 'kind', label: '类型', type: 'select', options: ['原料', '成品'], required: true },
      { key: 'cargoType', label: '货物类型', type: 'select', required: true, options: (form) => form.kind === '成品' ? ['混成品'] : ['达标矿', '报备矿'] },
      { key: 'source', label: '矿源', required: true, placeholder: '报备矿填写矿源', when: (form) => form.kind === '原料' && form.cargoType === '报备矿' },
    ],
    onFormChange(form, key) {
      if (key === 'kind' && form.kind === '成品') form.cargoType = '混成品'
      if (key === 'kind' && form.kind === '原料' && form.cargoType === '混成品') form.cargoType = '达标矿'
    },
    list: materialApi.list,
    create: materialApi.create,
    update: materialApi.update,
    exportRows: materialApi.exportRows,
  },
  filings: {
    key: 'filings',
    createLabel: '新建备案',
    filters: [
      { key: 'source', label: '矿源', type: 'select', options: ['智利矿源A', '秘鲁矿源B'] },
      { key: 'keyword', label: '备案编号' },
      { key: 'status', label: '状态', type: 'select', options: ['有效', '停用'] },
      { key: 'from', label: '备案起', type: 'date' },
      { key: 'to', label: '备案止', type: 'date' },
    ],
    columns: [
      { prop: 'code', label: '备案编号', minWidth: 140 },
      { prop: 'source', label: '矿源', minWidth: 120 },
      { prop: 'originCountry', label: '原产国', width: 100 },
      { prop: 'qty', label: '备案数量', width: 110 },
      { prop: 'usedQty', label: '核销', width: 90 },
      { prop: 'remain', label: '剩余', width: 90 },
      { prop: 'usage', label: '用量%', width: 90 },
      { prop: 'prodBatches', label: '生产批次号', minWidth: 140 },
      { prop: 'filingDate', label: '备案日期', width: 120 },
      { prop: 'status', label: '状态', width: 90, tag: true },
    ],
    form: [
      { key: 'code', label: '备案编号', required: true },
      { key: 'source', label: '矿源', required: true },
      { key: 'originCountry', label: '原产国', required: true },
      { key: 'qty', label: '备案数量', type: 'number', required: true },
      { key: 'filingDate', label: '备案日期', type: 'date', required: true },
      { key: 'prodBatches', label: '生产批次号' },
      { key: 'attachment', label: '附件', type: 'file' },
      { key: 'status', label: '状态', type: 'select', options: ['有效', '停用'], required: true },
    ],
    list: materialApi.filings,
    create: materialApi.createFiling,
    exportRows: materialApi.exportFilings,
    showDetail: true,
    async detail(row) {
      const res = await materialApi.lots(String(row.code))
      const blocks: DetailBlock[] = [{
        title: '备案票货',
        table: {
          columns: [
            { prop: 'customsNo', label: '报关单号', minWidth: 160 },
            { prop: 'prodBatch', label: '生产批次号', minWidth: 120 },
            { prop: 'consignor', label: '委托方' },
            { prop: 'wet', label: '湿吨', width: 80 },
            { prop: 'dry', label: '干吨', width: 80 },
            { prop: 'stack', label: '堆位' },
            { prop: 'status', label: '状态', tag: true },
          ],
          rows: res.success ? res.data : [],
        },
      }]
      return blocks
    },
    actions: [{
      label: '导出票货',
      request: async (row) => materialApi.exportLots(String(row.code)),
    }],
  },
  partners: {
    key: 'partners',
    createLabel: '新建主体',
    filters: [
      { key: 'keyword', label: '编码/名称' },
      { key: 'role', label: '角色', type: 'select', options: ['委托方', '物流账册主体', '流向企业'] },
    ],
    columns: [
      { prop: 'code', label: '编码', width: 120 },
      { prop: 'name', label: '名称', minWidth: 140 },
      { prop: 'role', label: '角色', width: 140 },
      { prop: 'phone', label: '联系电话', width: 140 },
      { prop: 'source', label: '来源', width: 120 },
      { prop: 'status', label: '状态', width: 90, tag: true },
    ],
    form: [
      { key: 'code', label: '编码', required: true, disabled: (_f, isEdit) => isEdit },
      { key: 'name', label: '名称', required: true },
      { key: 'role', label: '角色', type: 'select', options: ['委托方', '物流账册主体'], required: true },
      { key: 'phone', label: '联系电话' },
      { key: 'status', label: '状态', type: 'select', options: ['启用', '停用'], required: true },
    ],
    canEdit: (row) => row.source !== '出库识别',
    list: partnerApi.list,
    create: partnerApi.create,
    update: partnerApi.update,
  },
  bonded: {
    key: 'bonded',
    createLabel: '新建账册',
    filters: [
      { key: 'keyword', label: '关键字', placeholder: '编号 / 名称 / 报关单号' },
      { key: 'from', label: '预警起', type: 'date' },
      { key: 'to', label: '预警止', type: 'date' },
    ],
    columns: [
      { prop: 'code', label: '账册编号', minWidth: 130 },
      { prop: 'name', label: '名称', minWidth: 180 },
      { prop: 'operator', label: '经营单位', minWidth: 140 },
      { prop: 'value', label: '货值', width: 130 },
      { prop: 'customsNo', label: '报关单号', minWidth: 170 },
      { prop: 'status', label: '状态', width: 90, tag: true },
      { prop: 'warnDate', label: '旧账预警日', width: 130 },
    ],
    form: [
      { key: 'code', label: '账册编号', required: true, disabled: (_f, isEdit) => isEdit },
      { key: 'name', label: '名称', required: true },
      { key: 'operator', label: '经营单位', required: true },
      { key: 'value', label: '货值', type: 'number', required: true },
      { key: 'customsNo', label: '报关单号', required: true },
      { key: 'status', label: '状态', type: 'select', options: ['新账', '旧账'], required: true },
      { key: 'prevBook', label: '衔接旧账' },
      { key: 'warnDate', label: '旧账预警日', type: 'date' },
    ],
    list: bondedApi.list,
    create: bondedApi.create,
    update: bondedApi.update,
    showDetail: true,
    async detail(row) {
      const res = await bondedApi.lots(String(row.code))
      return [{
        title: `${row.code} 出入库票矿`,
        fields: [{ label: '规则', value: '新账须填旧账预警日；旧账只出不进；超预警未出库的入库数据转入新账。' }],
        table: {
          columns: [
            { prop: 'direction', label: '方向', width: 80 },
            { prop: 'customsNo', label: '报关单号', minWidth: 160 },
            { prop: 'blNo', label: '提单号' },
            { prop: 'wet', label: '湿吨', width: 80 },
            { prop: 'dry', label: '干吨', width: 80 },
            { prop: 'consignor', label: '对方' },
            { prop: 'time', label: '时间', minWidth: 150 },
          ],
          rows: res.success ? res.data : [],
        },
      }]
    },
  },
  users: {
    key: 'users',
    createLabel: '注册账号',
    filters: [{ key: 'keyword', label: '账号/姓名' }],
    columns: [
      { prop: 'username', label: '账号', width: 140 },
      { prop: 'name', label: '姓名', width: 120 },
      { prop: 'roleName', label: '角色', width: 120 },
      { prop: 'phone', label: '电话', width: 140 },
      { prop: 'status', label: '状态', width: 90, tag: true },
    ],
    form: [
      { key: 'username', label: '账号', required: true, disabled: (_f, isEdit) => isEdit },
      { key: 'name', label: '姓名', required: true },
      { key: 'password', label: '密码', required: true, when: (form) => !form.__isEdit },
      { key: 'roleKey', label: '角色', type: 'select', required: true, options: [
        { label: '系统管理员', value: 'admin' },
        { label: '仓管员', value: 'warehouse' },
        { label: '关务员', value: 'customs' },
      ] },
      { key: 'phone', label: '电话' },
      { key: 'status', label: '状态', type: 'select', options: ['启用', '停用'], required: true },
    ],
    list: authApi.users,
    create: authApi.createUser,
    update: authApi.updateUser,
  },
  inbound: {
    key: 'inbound',
    createLabel: '新建预约',
    filters: [
      { key: 'from', label: '开始日期', type: 'date' },
      { key: 'to', label: '结束日期', type: 'date' },
      { key: 'shipMode', label: '货运方式', type: 'select', options: ['集装箱', '散货'] },
      { key: 'oreType', label: '矿种' },
      { key: 'status', label: '状态', type: 'select', options: ['暂存码头', '待收货', '已入库', '混成品'] },
    ],
    columns: [
      { prop: 'time', label: '时间', minWidth: 150 },
      { prop: 'customsNo', label: '报关单号', minWidth: 170 },
      { prop: 'blNo', label: '提单号', width: 120 },
      { prop: 'shipName', label: '船名', width: 100 },
      { prop: 'oreType', label: '矿种', width: 100 },
      { prop: 'shipMode', label: '装运方式', width: 100 },
      { prop: 'containerCount', label: '柜数', width: 80 },
      { prop: 'consignor', label: '委托方', width: 110 },
      { prop: 'stackCode', label: '预定堆位', width: 110 },
      { prop: 'as', label: 'As', width: 70 },
      { prop: 'pb', label: 'Pb', width: 70 },
      { prop: 'cd', label: 'Cd', width: 70 },
      { prop: 'f', label: 'F', width: 70 },
      { prop: 'hg', label: 'Hg', width: 70 },
      { prop: 'status', label: '状态', width: 110, tag: true },
    ],
    form: [
      { key: 'shipName', label: '船名', required: true },
      { key: 'voyage', label: '航次' },
      { key: 'blNo', label: '提单号', required: true },
      { key: 'customsNo', label: '报关单号', required: true },
      { key: 'checklistNo', label: '核注清单', required: true },
      { key: 'amount', label: '金额', type: 'number', required: true },
      { key: 'oreType', label: '矿种', required: true },
      { key: 'shipMode', label: '装运方式', type: 'select', options: ['集装箱', '散货'], required: true },
      { key: 'containerCount', label: '集装箱柜数', type: 'number', when: (form) => form.shipMode === '集装箱', required: true },
      { key: 'consignor', label: '委托方', type: 'select', options: consignors, required: true },
      { key: 'stackCode', label: '预定堆位', type: 'select', options: stackCodes, required: true },
      { key: 'cells', label: '存放格子', placeholder: '如 1-1,1-2' },
      { key: 'time', label: '时间', type: 'datetime', required: true },
      { key: 'status', label: '状态', type: 'select', options: ['暂存码头', '待收货', '已入库', '混成品'], required: true },
    ],
    canEdit: (row) => row.status === '暂存码头' || row.status === '待收货',
    showDetail: (row) => row.status === '已入库' || row.status === '混成品',
    detail: (row) => [{
      title: '本票单证',
      fields: [
        { label: '报关单号', value: text(row.customsNo) },
        { label: '核注清单', value: text(row.checklistNo) },
        { label: '提单号', value: text(row.blNo) },
        { label: '预定堆位', value: text(row.stackCode) },
        { label: '存放格子', value: text(row.cells) },
        { label: '金额', value: text(row.amount) },
      ],
    }],
    list: inboundApi.list,
    create: inboundApi.create,
    update: inboundApi.update,
  },
  inventory: {
    key: 'inventory',
    filters: [
      { key: 'timeMode', label: '时间', type: 'select', options: [{ label: '不限', value: '' }, { label: '本月', value: 'month' }, { label: '自定义', value: 'range' }] },
      { key: 'from', label: '开始', type: 'date', when: (form) => form.timeMode === 'range' },
      { key: 'to', label: '结束', type: 'date', when: (form) => form.timeMode === 'range' },
      { key: 'consignor', label: '委托方', type: 'select', options: consignors },
      { key: 'warehouse', label: '仓库', type: 'select', options: houses },
      { key: 'areaLabel', label: '片区标识', type: 'select', options: areas },
      { key: 'cargoType', label: '货物类型', type: 'select', options: ['达标矿', '报备矿', '混成品'] },
      { key: 'status', label: '状态', type: 'select', options: ['在库', '已出库'] },
      { key: 'keyword', label: '批次/堆位' },
    ],
    columns: [
      { prop: 'batchNo', label: '批次号', minWidth: 170 },
      { prop: 'batchKind', label: '批次身份', width: 120 },
      { prop: 'consignor', label: '委托方', width: 110 },
      { prop: 'material', label: '物料', width: 100 },
      { prop: 'cargoType', label: '货物类型', width: 100 },
      { prop: 'warehouse', label: '仓库', width: 110 },
      { prop: 'stackText', label: '堆位', width: 110 },
      { prop: 'areaLabel', label: '片区', width: 100 },
      { prop: 'wet', label: '湿吨', width: 80 },
      { prop: 'dry', label: '干吨', width: 80 },
      { prop: 'originCountry', label: '原产国', width: 90 },
      { prop: 'status', label: '状态', width: 90, tag: true },
    ],
    showDetail: true,
    async detail(row) {
      const res = await inventoryApi.detail(String(row.batchNo))
      const data = res.success ? res.data : row
      const qualities = ['cu', 'ag', 'au', 'as', 'pb', 'cd', 'f', 'hg']
      return [
        {
          title: '本票品质',
          fields: qualities.map((key) => ({ label: key.toUpperCase(), value: text(data[key]) })),
        },
        {
          title: '单证与去向',
          fields: [
            { label: '批次身份', value: text(data.batchKind) },
            { label: '原产国', value: text(data.originCountry) },
            { label: '堆位', value: text(data.stackText) },
          ],
          table: {
            columns: [
              { prop: 'prodBatch', label: '成品批次', minWidth: 140 },
              { prop: 'output', label: '产量', width: 90 },
              { prop: 'stock', label: '库存', width: 90 },
              { prop: 'outbound', label: '出库', width: 90 },
            ],
            rows: (data.products as Record<string, unknown>[]) || [],
          },
        },
        {
          title: '重量台账',
          table: {
            columns: [
              { prop: 'time', label: '时间', minWidth: 150 },
              { prop: 'action', label: '业务', width: 100 },
              { prop: 'wet', label: '湿吨', width: 80 },
              { prop: 'dry', label: '干吨', width: 80 },
              { prop: 'stack', label: '堆位', width: 100 },
              { prop: 'consignee', label: '流向企业', minWidth: 120 },
            ],
            rows: (data.ledger as Record<string, unknown>[]) || [],
          },
        },
      ]
    },
    list: inventoryApi.list,
  },
  stocktake: {
    key: 'stocktake',
    createLabel: '新建盘点',
    filters: [{ key: 'month', label: '月份', placeholder: 'YYYY-MM' }],
    columns: [
      { prop: 'month', label: '月份', width: 110 },
      { prop: 'warehouses', label: '仓库范围', minWidth: 160 },
      { prop: 'stacks', label: '堆位范围', minWidth: 160 },
      { prop: 'attachment', label: '附件', minWidth: 140 },
      { prop: 'operator', label: '登记人', width: 110 },
      { prop: 'time', label: '时间', minWidth: 150 },
      { prop: 'remark', label: '备注', minWidth: 180 },
    ],
    form: [
      { key: 'month', label: '月份', required: true, placeholder: '2026-09' },
      { key: 'warehouses', label: '仓库', type: 'multi', options: houses, required: true, span: 24 },
      { key: 'stacks', label: '堆位', type: 'multi', options: stackCodes, required: true, span: 24 },
      { key: 'attachment', label: '附件', type: 'file' },
      { key: 'remark', label: '备注', type: 'textarea', span: 24 },
    ],
    list: stocktakeApi.list,
    create: stocktakeApi.create,
    monthExport: stocktakeApi.exportMonth,
  },
  alerts: {
    key: 'alerts',
    filters: [{ key: 'type', label: '类型', type: 'select', options: ['库容', '库龄', '码头超期', '备案用量'] }],
    columns: [
      { prop: 'type', label: '类型', width: 120, tag: true },
      { prop: 'target', label: '对象', minWidth: 180 },
      { prop: 'detail', label: '说明', minWidth: 320 },
      { prop: 'time', label: '时间', width: 140 },
    ],
    list: inventoryApi.alerts,
    actions: [{ label: '查看', pathFrom: 'link' }],
  },
  outbound: {
    key: 'outbound',
    createLabel: '新建出库',
    filters: [
      { key: 'from', label: '开始日期', type: 'date' },
      { key: 'to', label: '结束日期', type: 'date' },
      { key: 'status', label: '状态', type: 'select', options: ['待审核', '已审核'] },
    ],
    columns: [
      { prop: 'time', label: '出库时间', minWidth: 150 },
      { prop: 'customsNo', label: '报关单号', minWidth: 170 },
      { prop: 'checklistNo', label: '核注清单', minWidth: 120 },
      { prop: 'batchNo', label: '批次', minWidth: 140 },
      { prop: 'consignee', label: '流向企业', width: 120 },
      { prop: 'consumer', label: '消费使用单位', minWidth: 130 },
      { prop: 'wet', label: '重量', width: 90 },
      { prop: 'amount', label: '报关单金额', width: 120 },
      { prop: 'status', label: '状态', width: 100, tag: true },
    ],
    form: [
      { key: 'batchNo', label: '库存批次' },
      { key: 'customsNo', label: '报关单号', required: true },
      { key: 'checklistNo', label: '核注清单号', required: true },
      { key: 'consignee', label: '流向企业', required: true },
      { key: 'consumer', label: '消费使用单位', required: true },
      { key: 'wet', label: '重量', type: 'number', required: true },
      { key: 'amount', label: '报关单金额', type: 'number', required: true },
      { key: 'time', label: '出库时间', type: 'datetime', required: true },
      { key: 'remark', label: '备注', type: 'textarea', span: 24 },
    ],
    assist: {
      label: '识别出库报关单',
      fill: () => ({
        customsNo: '5301202600009902',
        checklistNo: 'QD9902',
        consignee: '华南冶炼',
        consumer: '华南冶炼',
        wet: 80,
        amount: 960000,
      }),
    },
    list: outboundApi.list,
    create: outboundApi.create,
    update: outboundApi.update,
    actions: [{
      label: '审核',
      when: (row) => row.status === '待审核',
      confirm: '确认审核通过该出库单？',
      request: (row) => outboundApi.approve(String(row.id)),
    }],
  },
  production: {
    key: 'production',
    createLabel: '登记投料',
    filters: [
      { key: 'consignor', label: '委托方', type: 'select', options: consignors },
      { key: 'from', label: '开始日期', type: 'date' },
      { key: 'to', label: '结束日期', type: 'date' },
    ],
    columns: [
      { prop: 'time', label: '时间', minWidth: 150 },
      { prop: 'prodBatch', label: '生产批次号', minWidth: 140 },
      { prop: 'consignor', label: '委托方', width: 110 },
      { prop: 'cargoType', label: '矿物', width: 100 },
      { prop: 'customsNos', label: '报关单号', minWidth: 220 },
      { prop: 'outCustomsNo', label: '出库报关单号', minWidth: 150 },
      { prop: 'process', label: '工序', width: 90 },
      { prop: 'wet', label: '干吨', width: 90 },
      { prop: 'stackCode', label: '堆位', width: 100 },
      { prop: 'stage', label: '状态', width: 90, tag: true },
    ],
    form: [
      { key: 'prodBatch', label: '生产批次号', required: true },
      { key: 'consignor', label: '委托方', type: 'select', options: consignors, required: true },
      { key: 'cargoType', label: '矿物', type: 'select', options: ['达标矿', '报备矿'], required: true },
      { key: 'customsNos', label: '报关单号', type: 'multi', options: customsNos, required: true, span: 24 },
      { key: 'outCustomsNo', label: '出库报关单号' },
      { key: 'wet', label: '投料干吨', type: 'number', required: true },
      { key: 'process', label: '工序', type: 'select', options: ['混矿', '筛分'], required: true },
      { key: 'time', label: '时间', type: 'datetime', required: true },
      { key: 'material', label: '物料' },
      { key: 'voyage', label: '船名/航次' },
      { key: 'blNo', label: '提单号' },
      { key: 'originCountry', label: '来源国家' },
    ],
    showDetail: true,
    detail: (row) => [{
      title: '批次详情',
      fields: [
        { label: '物料', value: text(row.material) },
        { label: '船名/航次', value: text(row.voyage) },
        { label: '提单号', value: text(row.blNo) },
        { label: '来源国家', value: text(row.originCountry) },
        { label: '挂接报关单', value: text(row.customsNos) },
        { label: '出库报关单号', value: text(row.outCustomsNo) },
        { label: '堆位', value: text(row.stackCode) },
      ],
    }],
    list: productionApi.list,
    create: productionApi.create,
    actions: [
      {
        label: '完工入库',
        when: (row) => row.stage === '投料' || row.stage === '加工',
        prompt: { title: '完工入库', message: '目标堆位仅限待检区，例如 4#A1', key: 'stackCode' },
        request: (row, extra) => productionApi.complete(String(row.id), String(extra.stackCode || '')),
      },
      {
        label: '查验完成',
        when: (row) => row.stage === '待检',
        confirm: '确认查验完成？堆位片区标识将改为成品区。',
        request: (row) => productionApi.inspect(String(row.id)),
      },
    ],
  },
  customs: {
    key: 'customs',
    filters: [{ key: 'status', label: '结果', type: 'select', options: ['一致', '有差异'] }],
    columns: [
      { prop: 'book', label: '账册', width: 140 },
      { prop: 'item', label: '项目', width: 120 },
      { prop: 'bookWet', label: '账册湿吨', width: 120 },
      { prop: 'stockWet', label: '库存湿吨', width: 120 },
      { prop: 'diff', label: '差异', width: 100 },
      { prop: 'status', label: '状态', width: 100, tag: true },
    ],
    showDetail: true,
    async detail(row) {
      const res = await customsApi.details(String(row.id))
      return [{
        title: '差异穿透',
        table: {
          columns: [
            { prop: 'checklistNo', label: '核注清单', minWidth: 120 },
            { prop: 'customsNo', label: '报关单号', minWidth: 160 },
            { prop: 'prodBatch', label: '生产批次号', minWidth: 140 },
            { prop: 'bookWet', label: '账册', width: 90 },
            { prop: 'stockWet', label: '库存', width: 90 },
            { prop: 'diff', label: '差异', width: 90 },
          ],
          rows: res.success ? res.data : [],
        },
      }]
    },
    list: customsApi.list,
    toolbar: [
      { label: '联网申报（预留）', run: () => customsApi.declare() },
      { label: '账册核销（预留）', run: () => customsApi.writeOff() },
    ],
  },
  ocr: {
    key: 'ocr',
    createLabel: '发起识别',
    filters: [{ key: 'docType', label: '单据', type: 'select', options: ['入库报关单', '出库报关单', '提单', '品质单', '重量单'] }],
    columns: [
      { prop: 'time', label: '时间', minWidth: 150 },
      { prop: 'docType', label: '单据类型', width: 120 },
      { prop: 'fileName', label: '文件', minWidth: 160 },
      { prop: 'customsNo', label: '报关单号', minWidth: 170 },
      { prop: 'checklistNo', label: '核注清单', width: 120 },
      { prop: 'consignee', label: '流向企业', width: 120 },
      { prop: 'confidence', label: '置信度', width: 90 },
      { prop: 'status', label: '状态', width: 100, tag: true },
    ],
    form: [
      { key: 'docType', label: '单据类型', type: 'select', options: ['入库报关单', '出库报关单', '提单', '品质单', '重量单'], required: true },
      { key: 'fileName', label: '文件名', type: 'file', required: true },
      { key: 'customsNo', label: '报关单号' },
      { key: 'checklistNo', label: '核注清单号' },
      { key: 'consignee', label: '流向企业' },
    ],
    list: ocrApi.list,
    create: ocrApi.recognize,
    update: ocrApi.update,
  },
  audit: {
    key: 'audit',
    filters: [
      { key: 'from', label: '开始日期', type: 'date' },
      { key: 'to', label: '结束日期', type: 'date' },
      { key: 'module', label: '模块', type: 'select', options: ['仓位管理', '堆位管理', '物料档案', '矿源备案', '往来主体', '保税账册', '入库管理', '库内移库', '盘点管理', '出库管理', '生产/完工', 'OCR识别', '系统设置', '平面图设置'] },
      { key: 'keyword', label: '操作人/单号' },
    ],
    columns: [
      { prop: 'time', label: '时间', minWidth: 150 },
      { prop: 'operator', label: '操作人', width: 110 },
      { prop: 'module', label: '模块', width: 120 },
      { prop: 'action', label: '动作', width: 120 },
      { prop: 'bizNo', label: '业务单号', minWidth: 160 },
      { prop: 'customsAccount', label: '关务账号', width: 100 },
    ],
    showDetail: true,
    detail: (row) => [{
      title: '留痕详情',
      fields: [
        { label: '操作人', value: text(row.operator) },
        { label: '来源地址', value: text(row.ip) },
        { label: '关务专用账号', value: text(row.customsAccount) },
        { label: '业务单号', value: text(row.bizNo) },
        { label: '修改前', value: text(row.before) },
        { label: '修改后', value: text(row.after) },
      ],
    }],
    list: auditApi.list,
  },
}

export function getSchema(name: string) {
  return schemas[name]
}
